# Site settings
title: koberg.com
username: rkoberg
email: rob@koberg.com
description: "Mostly on web development"
baseurl: ""
url: "http://rkoberg.github.io"
highlighter: pygments

# Build settings
markdown: kramdown
permalink: pretty
